# Generated by Django 5.2 on 2025-05-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ride_is_available_ride_is_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='is_driver',
        ),
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
