# Generated by Django 5.2 on 2025-05-06 06:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_remove_ride_is_available_remove_ride_is_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
